---
services:
  cloudflare-ddns:
    image: oznu/cloudflare-ddns:latest
    restart: unless-stopped
    environment:
      - API_KEY=<CLOUDFLARE_API_KEY>
      - ZONE=<BASE_DOMAIN>
      - SUBDOMAIN=<SUBDOMAIN>
      - PROXIED=false